name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - perl-version: '5.30'
            release-test: true
            coverage: true
          - perl-version: '5.10'
          - perl-version: '5.14'
          - perl-version: '5.20'
    container: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Graphviz, Perl and dependencies
        run: |
          apt-get -y update && apt-get -y install graphviz
          cpanm -n --installdeps .
      - name: perl -V
        run: perl -V
      - name: Run release tests # before others as may install useful stuff
        if: ${{ matrix.release-test }}
        env:
          RELEASE_TESTING: 1
        run: |
          cpanm -n --installdeps --with-develop .
          prove -lr xt
      - name: Run tests (no coverage)
        if: ${{ !matrix.coverage }}
        run: prove -l t
      - name: Run tests (with coverage)
        if: ${{ matrix.coverage }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          perl -MDevel::Cover::Report::Coveralls -mTest::More -e 'package Devel::Cover::Report::Coveralls; print Test::More::explain +{ %{ get_config() }, %{ get_git_info() } }'
          cover -test -report Coveralls
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Graphviz, Perl and dependencies (MacOS)
        run: |
          brew install graphviz perl
          curl -L https://cpanmin.us | perl - -n --installdeps .
      - name: perl -V
        run: perl -V
      - name: Run tests
        run: prove -l t
